### ISSUE TITLE
Linux make fatal error libusb-1.0/libusb.h No such file or directory

### ISSUE THREAD

**Issue by sizemoreap** [sergev/dmrconfig#13]
Title says it all. Upon running make, 

dfu0libusb.c:32:10: fatal error: libusb-1.0/libusb.h: No such file or directory

Fedora 29, btw.

**Comment by simonvik** [comment]
A bit of googling points towards libusbx-devel on fedora, does that give you the header-file?

**Comment by sergev** [comment]
Please install libusb-1.0 before running make:
```
sudo yum install libusbx-devel
```
