### ISSUE TITLE
BTECH DMR-6x2'

### ISSUE THREAD

**Issue by prokrypt** [sergev/dmrconfig#14]
Hi! The BTECH DMR-6x2 is basically an Anytone D868UV with the addition of recording hardware (?) and some extra features. It supposedly supports D868UV code plugs. I am available for testing if needed.

```
$ dmrconfig -r
Serial port: /dev/ttyACM0
Unrecognized radio 'D6X2UV'.
```

**Comment by sergev** [comment]
Excellent! Looks like DMR-6x2 has the same protocol, and hopefully the same address map. I've modified dmrconfig to properly detect this radio. Please try version 16d7bbac5d3e0dcf611dbbdcf1f286276b59172f.

**Comment by prokrypt** [comment]
Awesome! \o/
```
$ dmrconfig -c device.conf
Serial port: /dev/ttyACM0
Connect to BTECH DMR-6x2.
Read device: ##### done.
Write codeplug to file 'backup.img'.
Read configuration from file 'device.conf'.
Total 13 channels, 1 zones, 1 scanlists, 6 contacts, 1 grouplists.
Write device: ##### done.
Close device.
```

**Comment by sergev** [comment]
Perfect! Now I can add BTECH DMR-6x2 to the list of supported devices.
Can you please give me a favor: create a virgin empty image for my collection?
Like this:

(1) Create a backup image and save it for later: 
```
dmrconfig -r
mv device.img backup-2018-11-09.img
```
(2) Reset the radio with poweroff, PTT+PF1 key, poweron, confirm.

(3) Read the virgin image:
```
dmrconfig -r
mv device.img dmr6x2-empty.img
```

(4) Restore your codeplug with:
```
dmrconfig -w backup-2018-11-09.img
```
Please send me the resulting dmr6x2-empty.img file.
Thank you!

**Comment by prokrypt** [comment]
I'm no good with github. Hopefully this works
[dmr6x2-empty.zip](https://github.com/sergev/dmrconfig/files/2568127/dmr6x2-empty.zip)

**Comment by sergev** [comment]
Thank you so much!
Exactly what I need. 
I use these images for regression testing.

**Comment by prokrypt** [comment]
Whups. Bugs possibly due to new features of the radio: Scanlist setting for each channel doesn't function correctly. When viewing the scanlist on any channel after a new upload, the first list is repeated 8 times no matter what was set in device.conf. It seems like it's only possible to delete them one by one from the radio starting with the last item.

In device.conf, if I set a channel's scan list to "-", it turns on "channel measure" mode for that channel, causing the radio to automatically transmit at intervals (very bad!).

The DMR-6X2 supports multiple scanlists per channel--I'm not sure if the D868UV is the same.

dmrconfig very usable for this radio, but for now the scan list portion of it may be a bit dangerous.

**Comment by prokrypt** [comment]
I decided to do some diffing on the device.img. I don't really know how to computer, so please forgive me if this isn't the proper Way Of The Coder~

command used: `diff -a <(hexdump -C image1.img) <(hexdump -C image2.img)`

Change to channel 1 (probably from channel 8?)
```
< 00071700  07 00 0b 00 19 00 94 30  a3 47 a2 c3 ab 05 d4 ee  |.......0.G......|
---
> 00071700  00 00 0b 00 19 00 94 30  a3 47 a2 c3 ab 05 d4 ee  |.......0.G......|
```

Delete one out of the 8 scanlist duplicates from channel 1
```
< 00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
---
> 00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 ff 00 00  |................|
```

Delete all but one
```
< 00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 ff 00 00  |................|
---
> 00000070  00 00 00 00 00 00 00 ff  ff ff ff ff ff ff 00 00  |................|
```

Add a scanlist #2 (so now there are two total, 00 and 01)
```
< 00000070  00 00 00 00 00 00 00 ff  ff ff ff ff ff ff 00 00  |................|
---
> 00000070  00 00 00 00 00 00 00 01  ff ff ff ff ff ff 00 00  |................|
```

**Comment by sergev** [comment]
Thank you for detailed hexdumps. Seems like dmr6x2 uses last ten bytes of channel data structure for different purposes. 

D868UV:
byte 27: scan list index: 0xff=None, 0=ScanList1 and so on
byte 54: APRS Report Channel
bytes 55-61: unused

DMR-6x2:
byte 27: channel measure mode: 0=Off, 1=On
bytes 54-61: eight scan list indices: 0xff=None, 0=ScanList1 and so on

Index list at 00071700 is OK: these are current channels for every zone. I've fixed this issue in 767d64f93375f03977baaa2caf7b3e9a838eb5b9.

I'll modify dmrconfig to accomodate the above differences.

**Comment by sergev** [comment]
Please try eb9bba910687cb2a64f6e53dbf1d51e3a152ae3b.

**Comment by prokrypt** [comment]
Success! \o/ Setting scanlists (or not setting them) works~

**Comment by sergev** [comment]
Great! Now I'm almost ready to release a new dmrconfig-1.0 binary package. Just need to implement updating of callsign database.

From a review of new Alinco DJ-MD5T, it looks like an enhanced variant of D868UV. It should be pretty easy to add a support for it as well.

**Comment by sergev** [comment]
Scan list index was still printed incorrectly for DMR-6x2. 
Here is the fix: 61e015b1a05a833ce2f082d6c68a0b59012f1009.

**Comment by prokrypt** [comment]
Er, not really sure what went wrong or what changed, but the latest one works just as well~ wheeee \o/

**Comment by sergev** [comment]
Indices for Scanlist2, Scanlist3 and so on were printed incorrectly in the Channel table.

**Comment by sjlongland** [comment]
Hate to bump an old issue… anyone know if this feature applies to the DMR-6x2 Pro as well?

My old Kenwood TH-D72A died (well, it works but no longer charges or runs from a battery) and I'm looking for a replacement that does VHF APRS (Bell 203 modulation, aka 1200 baud AFSK), and sadly Kenwood no longer sell amateur radios here in Australia.  The BTech DMR-6x2 (non-PRO) does APRS but it's TX only, the PRO version apparently receives as well.

If this software can work with this model radio, I might give it and `dmrconfig` a look. :-)

**Comment by EntropyWorks** [comment]
Just poking to see if BTech DMR-6x2 Pro is in the works.

```
$ ./dmrconfig -r -t
Cannot find USB device 0483:df11
Cannot find USB device 15a2:0073
Serial port: /dev/ttyACM0
----Send [7] 50-52-4f-47-52-41-4d
----Recv [3] 51-58-06
----Send [1] 02
----Recv [16] 49-44-36-58-32-55-56-32-00-56-31-30-30-00-00-06
Unrecognized radio 'D6X2UV2'.
```
