### ISSUE TITLE
CSV Contacts uploaded on DMR-6X2, but no worky

### ISSUE THREAD

**Issue by prokrypt** [sergev/dmrconfig#16]
```
$ dmrconfig -u users.csv 
Serial port: /dev/ttyACM0
Connect to BTECH DMR-6x2.
Read file 'users.csv'.
Total 114091 contacts, 6009567 bytes.
Write: ###################################################################### done.
```
Looks like it was successful, but radio still doesn't show contact info on incoming transmissions ¯\\_(ツ)_/¯
Sample of uploaded users.csv:
```
Radio ID,Callsign,Name,City,State,Country,Remarks
1023001,VE3THW,Wayne Edward,Toronto,Ontario,Canada,DMR
1023002,VA3ECM,Mathieu Goulet,Ottawa-Hull,Quebec,Canada,CCS7
```

Also, looks like it doesn't support the format of certain files:
```
Serial port: /dev/ttyACM0
Connect to BTECH DMR-6x2.
Read file 'contacts_20181121060901.csv'.
Total 0 contacts, 1 bytes.
Write: ## done.
Close device.
```
Sample:
```
"No.","Radio ID","Callsign","Name","City","State","Country","Remarks","Call Type","Call Alert"
"","6034","GJ7LJJ","Nigel Utting","St. Saviour","Jersey","United Kingdom","","",""
"","44300","GW1SYG","Andy","Deeside","","United Kingdom","","",""
```

**Comment by sergev** [comment]
Same here. Looks like something is still wrong with offset in the callsign map. I'm working on it.

Other files may have different number of fields. Not a big problem, just need to update the CSV parser to handle these cases.

**Comment by sergev** [comment]
Try 08ae73121857d549bad28983ad3c34f371bb715a: it seems to work correctly with CSV files obtained from https://www.radioid.net/static/users.csv

**Comment by prokrypt** [comment]
![img_20181123_191555](https://user-images.githubusercontent.com/1832555/48964027-860b9f00-ef54-11e8-9224-950cdbe5e50d.jpg)
\o/

**Comment by sergev** [comment]
Excellent!
In 46203f940ea253e00052c8d52f5de71098eae1ec I've also added support for amateurradio.digital CSV file format.
