### ISSUE TITLE
Please clarify the license

### ISSUE THREAD

**Issue by irl** [sergev/dmrconfig#33]
The text of the Apache License version 2.0 is included, but all the files have BSD-3-clause headers where there are copyright statements.

Given that most of the project is distributed with BSD-3-clause headers, it would make sense to just replace the LICENSE file with the text of the BSD-3-clause license as this is the only place the Apache license is referenced.

This blocks Debian packaging, [debian#934219](https://bugs.debian.org/934219).

**Comment by sergev** [comment]
Thank you for noticing this issue, Iain.
Fixed in b60cad10f6db70d3895150979b3ec80667df5775.

**Comment by xlfe** [comment]
@sergev  just wanted to say thank you for all your work on dmrconfig - just tried it out and it worked flawlessly!

**Comment by sergev** [comment]
@xlfe You are welcome, Felix!
