### ISSUE TITLE
A way to delete/erase old entries

### ISSUE THREAD

**Issue by davebdb** [sergev/dmrconfig#47]
It seems that the commands here just add and update-append the main codeplug.  Is there a way to delete entries that are no longer wanted in the memory of the codeplug.  I've been testing this with my RD-5R and have entries that I made as test entries and they are still present in the codeplug.  Is there a way to delete them and force the memory entries to be whatever is in the codeplug script?

**Comment by sergev** [comment]
Not exactly, it does not append. When your config script contains any channels defined, the dmrconfig tool completely erases existing channels/zones/scanlists and uses new data from your script.

**Comment by davebdb** [comment]
I found my problem was I still had the zones created, even though I renamed the channels.  Thanks for the clarification and work on this program.  I've tested it on the RD-5R so far, but not my TYT-380 yet.
-closing ticket
