### ISSUE TITLE
Can't write out device config from UV380

### ISSUE THREAD

**Issue by sonyccd** [sergev/dmrconfig#5]
```
$ ./dmrconfig -c device.img device.conf 
Read codeplug from file 'device.img'.
Last Programmed Date: 2018-09-12 15:11:57
CPS Software Version: V01.06
Read configuration from file 'device.conf'.
Bad value for Radio: TYT MD-UV390
```

**Comment by sergev** [comment]
Oops... Sure this is a bug. Brad, can you please attach your device.img and device.conf files?

**Comment by sergev** [comment]
As a temporary workaround: just open the file device.conf in any text editor and modify the line:
```
Radio: TYT MD-UV390
```
to make it:
```
Radio: TYT MD-UV380
```

**Comment by sergev** [comment]
Fixed in 8be79da3e0aad80ad7fd3f8cae0019495000693b.

**Comment by sergev** [comment]
@sonyccd : Please try release 0.7, now it should work correctly.
https://raw.githubusercontent.com/wiki/sergev/dmrconfig/releases/dmrconfig-0.7.zip

**Comment by sonyccd** [comment]
Will try and update you

**Comment by sergev** [comment]
Seems like this issue has been resolved.
