### ISSUE TITLE
Add supported device Baofeng TD-5R Dual Time Slot

### ISSUE THREAD

**Issue by etu** [sergev/dmrconfig#7]
I've bought this radio https://www.aliexpress.com/item//32870368262.html and ended up having a hard time to configure it under Linux until a friend pointed out this project.

So I've tried it and it works with my radio perfectly fine as far as I can see and test.

I've also wrote a package for NixOS, but it's not in any release channel yet :-)
https://github.com/NixOS/nixpkgs/pull/49052

As far as I can see it's only packaged by AUR so far: https://repology.org/metapackage/dmrconfig/versions

If you like to you could add a badge to the repo with the info for where it's packaged for an easy overview of which distros who have you package.

Just this in the readme should do it:
```
[![Packaging status](https://repology.org/badge/vertical-allrepos/dmrconfig.svg)](https://repology.org/metapackage/dmrconfig/versions)
```

**Comment by sergev** [comment]
Thank you so much, Elis! It's nice to have a dmrconfig package. But as I can see from https://aur.archlinux.org/packages/dmrconfig-git, the dependency list is incorrect: no need for ncurses. And probably libusb-1.0 and udev should be added.

I didn't know TD-5R is the same radio as RD-5R. I'll add it to the list of supported models. Looks like Baofeng is adding even more mess to their line of DMR enabled radios. :) Now we have four different names: BF-5R, DM-5R, RD-5R and TD-5R. People get easily confused.

I've updated readme with repology status, thanks.

**Comment by etu** [comment]
> Thank you so much, Elis! It's nice to have a dmrconfig package. But as I can see from https://aur.archlinux.org/packages/dmrconfig-git, the dependency list is incorrect: no need for ncurses. And probably libusb-1.0 and udev should be added.

I have nothing with the AUR one to do, but I'm a bit surprised that they list ncurses because their packagebuild doesn't mention it: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=dmrconfig-git

But it does mention libusb-1.0

> I didn't know TD-5R is the same radio as RD-5R. I'll add it to the list of supported models. Looks like Baofeng is adding even more mess to their line of DMR enabled radios. :) Now we have four different names: BF-5R, DM-5R, RD-5R and TD-5R. People get easily confused.

I was very confused when I bought mine... But I think I got a good one because I've managed to do DMR with the DMR Repeaters around where I live.

> I've updated readme with repology status, thanks.

Very cool! Thanks :-)

**Comment by simonvik** [comment]
I've removed ncurses now!

**Comment by sergev** [comment]
Thank you, Simon!
